### ISSUE TITLE
Support for OAuth client_credenitals flow

### ISSUE THREAD

**Issue by druminik** [nmasse-itix/threescale-cicd#37]
When deploying an API secured by OAuth client_credentials flow the deployment fails during step "Update ActiveDocs" with error message "The property '#/securityDefinitions/oauth' of type Hash did not match any of the required schemas in schema http://swagger.io/v2/schema.json#\".
See sample swagger file attached and detailed error report.

[swagger_and_error.zip](https://github.com/nmasse-itix/threescale-cicd/files/2787833/swagger_and_error.zip)

**Comment by nmasse-itix** [comment]
Hi @druminik. 

Thanks for trying this project !

This error means the 3scale admin portal rejected the Swagger file because it failed to valide it against the official schema. 

This swagger doc is updated by the playbook before upload with contextualized URLs (`host:`, token and auth urls, etc.). So, to know what is going wrong, we need to get the patched swagger. 

Could you run the playbook again with the `-v` flag and attach the failing step and the debug steps just before ? **Do not forget to remove your 3scale access token from the log before uploading it !**

**Comment by druminik** [comment]
Hi Nicolas

thanks for the fast reply. Here's the log messages for the playbook run with -v  flag.

Regards


[error.zip](https://github.com/nmasse-itix/threescale-cicd/files/2790768/error.zip)

**Comment by nmasse-itix** [comment]
Hi @druminik !

Thanks to you logs, I found the issue. The `authorizationUrl` and `tokenUrl` were set unconditionally and that breaks the compliance with the Swagger 2.0 specifications that accepts combinations of those fields according to the oauth flow used. 

PR #38 is about this. The automated CI tests are currently running. If everything is fine, I will release a `1.0.1` today.

**Comment by nmasse-itix** [comment]
Hi @druminik ! Did you had a chance to try the 1.0.1 release that fixes your issue ?

**Comment by nmasse-itix** [comment]
Hi @druminik. I will close this issue. Feel free to re-open it if you still encounter this problem.
